server:
  port: 8888

spring:
  application:
    name: gateway-service
    
  # auto update config
  rabbitmq:
    host: localhost
    
  zipkin:
    base-url: http://127.0.0.1:9411/
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1
      
  # database
  datasource:
    password: AppleMan922
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/myBlog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC%2D8

  # Redis
  redis:
    host: localhost
    port: 6379

  servlet:
    multipart:
      # single file size
      max-file-size: 5MB
      # image size limit
      # total size
      max-request-size: 20MB

  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
      routes:
        # route http://localhost:8888/articles/* to article-service
        - id: articles
          uri: lb://article-service
          predicates:
            - Path=/articles/**
        - id: articles-all
          uri: lb://article-service
          predicates:
            - Path=/articles
        - id: comments
          uri: lb://article-service
          predicates:
            - Path=/comments/**
        - id: upload
          uri: lb://article-service
          predicates:
            - Path=/upload/**

        # route http://localhost:8888/categorys/* to category-service
        - id: category
          uri: lb://category-service
          predicates:
            - Path=/categorys/**
        - id: tags
          uri: lb://category-service
          predicates:
            - Path=/tags/**

        - id: login
          uri: lb://user-service
          predicates:
            - Path=/login/**
        - id: logout
          uri: lb://user-service
          predicates:
            - Path=/logout/**
        - id: register
          uri: lb://user-service
          predicates:
            - Path=/register/**
        - id: users
          uri: lb://user-service
          predicates:
            - Path=/users/**

    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        instance-id: ${spring.application.name}:${server.port}
        service-name: ${spring.application.name}
        port: ${server.port}
        prefer-ip-address: true
        ip-address: ${spring.cloud.client.ip-address}

        # check availability
        heartbeat:
          enabled: true
        health-check-interval: 10s
        health-check-critical-timeout: 10s

# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_
  mapper-locations: classpath:/com/project/myBlog/dao/mapper/*.xml
