# server
server:
  port: 9000

spring:
  application:
    name: user-service
    
  # auto update config
  rabbitmq:
    host: localhost
    
  # consul config
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        instance-id: ${spring.application.name}:${server.port}
        service-name: ${spring.application.name}
        port: ${server.port}
        prefer-ip-address: true
        ip-address: ${spring.cloud.client.ip-address}

        # check availability
        heartbeat:
          enabled: true
        health-check-interval: 10s
        health-check-critical-timeout: 10s

# database
  datasource:
    password: AppleMan922
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/myBlog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC%2D8

  # Redis
  redis:
    host: localhost
    port: 6379

  servlet:
    multipart:
      # single file size
      max-file-size: 5MB
      # image size limit
      # total size
      max-request-size: 20MB

# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_
  mapper-locations: classpath:/com/project/myBlog/dao/mapper/*.xml
